baseURL: https://enochack.com/
languageCode: en-us
title: Enochack
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

menu:
  main:
    - name: Search
      url: search/
      weight: 5
    - name: Categories
      url: categories/
      weight: 10
    - name: Tags
      url: tags/
      weight: 15
    - name: Archive
      url: archives/
      weight: 20
    - name: Mail
      url: mailto:dawnshepherd0909@gmail.com

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  defaultTheme: auto
  description: "Enochack"
  author: "Me"
  keywords: [Tech, DBMS, Gaming]
  ShowToc: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: false
  disableSpecial1stPost: true
  ShowPostNavLinks: true
  ShowRssButtonInSectionTermList: true
  hideFooter: false