# baseURL: https://enochack.com/
languageCode: en-us
title: Enochack
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45
enableGitInfo: true

menu:
  main:
    - name: Search
      url: search/
      weight: 5
    - name: Categories
      url: categories/
      weight: 10
    - name: Tags
      url: tags/
      weight: 15
    - name: Archive
      url: archives/
      weight: 20
    - name: CV
      url: cv/
      weight: 22
    - name: Mail
      weight: 25
      url: mailto:enoch.tsao@outlook.com

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  defaultTheme: auto
  description: "Enochack"
  author: "Enoch"
  keywords: ["Tech", "DBMS", "Data Lakehouse", "SQL Engine", "Gaming"]
  ShowToc: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: false
  disableSpecial1stPost: true
  ShowPostNavLinks: true
  ShowRssButtonInSectionTermList: true
  hideFooter: false
